opencost:
  image:
    repository: quay.io/opencost/opencost
    tag: "1.104.0"
  
  # Dashboard UI settings
  ui:
    enabled: true
  
  # Prometheus abhi ke liye band, taaki UI bina error ke khule
  prometheus:
    internal:
      enabled: false
    external:
      enabled: false

  # Basic Resources
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
