prometheus:
  internal:
    enabled: false
  external:
    enabled: true
    url: http://prometheus-server.monitoring.svc.cluster.local

ui:
  enabled: true

extraEnv:
  - name: PROMETHEUS_SERVER_ENDPOINT
    value: http://prometheus-server.monitoring.svc.cluster.local

cloudCost:
  enabled: false

# 🔥 THIS IS THE KEY FIX
startupProbe:
  enabled: false
readinessProbe:
  enabled: false
livenessProbe:
  enabled: false

service:
  type: ClusterIP

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
